export const IPC = {
  connections: {
    list: 'connections:list',
    save: 'connections:save',
    remove: 'connections:remove',
    export: 'connections:export',
    import: 'connections:import',
  },
  zk: {
    connect: 'zk:connect',
    disconnect: 'zk:disconnect',
    getStatus: 'zk:getStatus',
    listChildren: 'zk:listChildren',
    getData: 'zk:getData',
    setData: 'zk:setData',
    create: 'zk:create',
    remove: 'zk:remove',
    getAcl: 'zk:getAcl',
    setAcl: 'zk:setAcl',
    search: 'zk:search',
    executeCli: 'zk:executeCli',
    completePath: 'zk:completePath',
    fourLetter: 'zk:fourLetter',
  },
  monitor: {
    start: 'monitor:start',
    stop: 'monitor:stop',
    getLatest: 'monitor:getLatest',
    getHistory: 'monitor:getHistory',
    getAlerts: 'monitor:getAlerts',
  },
  settings: {
    get: 'settings:get',
    set: 'settings:set',
  },
  logs: {
    list: 'logs:list',
    clear: 'logs:clear',
  },
  events: {
    connectionStatus: 'event:connectionStatus',
    nodeChildrenChanged: 'event:nodeChildrenChanged',
    nodeDataChanged: 'event:nodeDataChanged',
    log: 'event:log',
    monitorSample: 'event:monitorSample',
    monitorAlert: 'event:monitorAlert',
    menuImport: 'event:menuImport',
    menuExport: 'event:menuExport',
    menuExportSecrets: 'event:menuExportSecrets',
  },
} as const
