// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function Connect(arg1:string):Promise<void>;

export function CreateNode(arg1:string,arg2:string,arg3:string,arg4:boolean,arg5:boolean):Promise<string>;

export function DeleteNode(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function Disconnect(arg1:string):Promise<void>;

export function DuplicateConnection(arg1:string):Promise<model.ConnectionProfile>;

export function GetData(arg1:string,arg2:string):Promise<model.ZkNodeData>;

export function GetSettings():Promise<model.AppSettings>;

export function GetStatus(arg1:string):Promise<model.ConnectionStatus>;

export function ListChildren(arg1:string,arg2:string):Promise<Array<model.ZkChildNode>>;

export function ListConnections():Promise<Array<model.ConnectionProfile>>;

export function RemoveConnection(arg1:string):Promise<void>;

export function RenameConnection(arg1:string,arg2:string):Promise<model.ConnectionProfile>;

export function SaveConnection(arg1:model.ConnectionProfile):Promise<model.ConnectionProfile>;

export function SetData(arg1:string,arg2:string,arg3:string,arg4:number):Promise<model.ZkStat>;

export function SetSettings(arg1:model.AppSettings):Promise<model.AppSettings>;
