// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function CreateNode(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateNode'](arg1, arg2, arg3, arg4, arg5);
}

export function DeleteNode(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteNode'](arg1, arg2, arg3);
}

export function Disconnect(arg1) {
  return window['go']['main']['App']['Disconnect'](arg1);
}

export function DuplicateConnection(arg1) {
  return window['go']['main']['App']['DuplicateConnection'](arg1);
}

export function GetData(arg1, arg2) {
  return window['go']['main']['App']['GetData'](arg1, arg2);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStatus(arg1) {
  return window['go']['main']['App']['GetStatus'](arg1);
}

export function ListChildren(arg1, arg2) {
  return window['go']['main']['App']['ListChildren'](arg1, arg2);
}

export function ListConnections() {
  return window['go']['main']['App']['ListConnections']();
}

export function RemoveConnection(arg1) {
  return window['go']['main']['App']['RemoveConnection'](arg1);
}

export function RenameConnection(arg1, arg2) {
  return window['go']['main']['App']['RenameConnection'](arg1, arg2);
}

export function SaveConnection(arg1) {
  return window['go']['main']['App']['SaveConnection'](arg1);
}

export function SetData(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetData'](arg1, arg2, arg3, arg4);
}

export function SetSettings(arg1) {
  return window['go']['main']['App']['SetSettings'](arg1);
}
